# permissions for end users to view redisstandalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisstandalone-viewer-role
rules:
- apiGroups:
  - redis.my.domain
  resources:
  - redisstandalones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.my.domain
  resources:
  - redisstandalones/status
  verbs:
  - get
